# Site settings
title: Demon404
header-img: "img/tree.jpg"
tagline: "吉光片羽"
description: "不忘初心，方得始终！"
baseurl: ""
url: "http://azeril.me"
#url: "http://localhost:4000"

# About/contact
owner:
  name: "Demon404"
  email: demonshow404@gmail.com
  bio: "我有故事，你要听吗？"

# Data
gavatar: "https://pic.cnblogs.com/avatar/820858/20160808171031.png"
favicon: img/favicon.ico

douban_username: ''
twitter_username: Demon4004
github_username: Demon404
facebook_username: Demon404
weibo_username: Demon404
zhihu_username: Demon404

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


gems:
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Demon404"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : Demon404
  disqus :
      short_name : Demon404

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
